// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AckMessagesFromTopicRequest defines model for ackMessagesFromTopicRequest.
type AckMessagesFromTopicRequest struct {
	// AckIds List of ids to acknowledge.
	AckIds []string `json:"ackIds"`
}

// Message defines model for message.
type Message struct {
	// AckId An auto generated unique id for acknowledging the message.
	AckId string `json:"ackId"`

	// CreateTime The point in time the resource was created.
	CreateTime time.Time `json:"createTime"`

	// Data Base64 encoded messages.
	Data []byte `json:"data"`

	// DeliveryAttempts Number of times the message has been tried to be delivered.
	DeliveryAttempts uint64 `json:"deliveryAttempts"`

	// Id A unique, increasing sequence number identifying the message within the topic.
	Id uint64 `json:"id"`
}

// Messages defines model for messages.
type Messages struct {
	Messages []Message `json:"messages"`
}

// NackMessagesFromTopicRequest defines model for nackMessagesFromTopicRequest.
type NackMessagesFromTopicRequest struct {
	// NackIds List of ids to not acknowledge.
	NackIds []string `json:"nackIds"`
}

// PublishMessage defines model for publishMessage.
type PublishMessage struct {
	// Data Base64 encoded message payload.
	Data []byte `json:"data"`
}

// PublishMessageResponse defines model for publishMessageResponse.
type PublishMessageResponse struct {
	MessageIds []uint64 `json:"messageIds"`
}

// PublishMessageToTopicRequest defines model for publishMessageToTopicRequest.
type PublishMessageToTopicRequest struct {
	// Messages The messages to publish.
	Messages []PublishMessage `json:"messages"`
}

// SubscriptionId defines model for subscriptionId.
type SubscriptionId = openapi_types.UUID

// PullMessagesParams defines parameters for PullMessages.
type PullMessagesParams struct {
	// PubSubMaxMessages The maximum number of messages to pull.
	PubSubMaxMessages *int32 `json:"PubSub-Max-Messages,omitempty"`

	// PubSubLongPullDuration The maximum amount of milliseconds to keep an connection open, awaiting a new message on the server.
	PubSubLongPullDuration *int32 `json:"PubSub-Long-Pull-Duration,omitempty"`
}

// PublishMessagesJSONRequestBody defines body for PublishMessages for application/json ContentType.
type PublishMessagesJSONRequestBody = PublishMessageToTopicRequest

// AckMessagesJSONRequestBody defines body for AckMessages for application/json ContentType.
type AckMessagesJSONRequestBody = AckMessagesFromTopicRequest

// NackMessagesJSONRequestBody defines body for NackMessages for application/json ContentType.
type NackMessagesJSONRequestBody = NackMessagesFromTopicRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PublishMessagesWithBody request with any body
	PublishMessagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublishMessages(ctx context.Context, body PublishMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PurgeTopic request
	PurgeTopic(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AckMessagesWithBody request with any body
	AckMessagesWithBody(ctx context.Context, subscriptionId SubscriptionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AckMessages(ctx context.Context, subscriptionId SubscriptionId, body AckMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// NackMessagesWithBody request with any body
	NackMessagesWithBody(ctx context.Context, subscriptionId SubscriptionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	NackMessages(ctx context.Context, subscriptionId SubscriptionId, body NackMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PullMessages request
	PullMessages(ctx context.Context, subscriptionId SubscriptionId, params *PullMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PublishMessagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishMessagesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishMessages(ctx context.Context, body PublishMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishMessagesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PurgeTopic(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPurgeTopicRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AckMessagesWithBody(ctx context.Context, subscriptionId SubscriptionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAckMessagesRequestWithBody(c.Server, subscriptionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AckMessages(ctx context.Context, subscriptionId SubscriptionId, body AckMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAckMessagesRequest(c.Server, subscriptionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NackMessagesWithBody(ctx context.Context, subscriptionId SubscriptionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNackMessagesRequestWithBody(c.Server, subscriptionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NackMessages(ctx context.Context, subscriptionId SubscriptionId, body NackMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNackMessagesRequest(c.Server, subscriptionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PullMessages(ctx context.Context, subscriptionId SubscriptionId, params *PullMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPullMessagesRequest(c.Server, subscriptionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPublishMessagesRequest calls the generic PublishMessages builder with application/json body
func NewPublishMessagesRequest(server string, body PublishMessagesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublishMessagesRequestWithBody(server, "application/json", bodyReader)
}

// NewPublishMessagesRequestWithBody generates requests for PublishMessages with any type of body
func NewPublishMessagesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1beta/publish")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPurgeTopicRequest generates requests for PurgeTopic
func NewPurgeTopicRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1beta/purge")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAckMessagesRequest calls the generic AckMessages builder with application/json body
func NewAckMessagesRequest(server string, subscriptionId SubscriptionId, body AckMessagesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAckMessagesRequestWithBody(server, subscriptionId, "application/json", bodyReader)
}

// NewAckMessagesRequestWithBody generates requests for AckMessages with any type of body
func NewAckMessagesRequestWithBody(server string, subscriptionId SubscriptionId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "subscriptionId", subscriptionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1beta/subscriptions/%s/ack", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewNackMessagesRequest calls the generic NackMessages builder with application/json body
func NewNackMessagesRequest(server string, subscriptionId SubscriptionId, body NackMessagesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNackMessagesRequestWithBody(server, subscriptionId, "application/json", bodyReader)
}

// NewNackMessagesRequestWithBody generates requests for NackMessages with any type of body
func NewNackMessagesRequestWithBody(server string, subscriptionId SubscriptionId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "subscriptionId", subscriptionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1beta/subscriptions/%s/nack", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPullMessagesRequest generates requests for PullMessages
func NewPullMessagesRequest(server string, subscriptionId SubscriptionId, params *PullMessagesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "subscriptionId", subscriptionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1beta/subscriptions/%s/pull", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.PubSubMaxMessages != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "PubSub-Max-Messages", *params.PubSubMaxMessages, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "integer", Format: "int32"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PubSub-Max-Messages", headerParam0)
		}

		if params.PubSubLongPullDuration != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "PubSub-Long-Pull-Duration", *params.PubSubLongPullDuration, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "integer", Format: "int32"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PubSub-Long-Pull-Duration", headerParam1)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PublishMessagesWithBodyWithResponse request with any body
	PublishMessagesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishMessagesResponse, error)

	PublishMessagesWithResponse(ctx context.Context, body PublishMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishMessagesResponse, error)

	// PurgeTopicWithResponse request
	PurgeTopicWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PurgeTopicResponse, error)

	// AckMessagesWithBodyWithResponse request with any body
	AckMessagesWithBodyWithResponse(ctx context.Context, subscriptionId SubscriptionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AckMessagesResponse, error)

	AckMessagesWithResponse(ctx context.Context, subscriptionId SubscriptionId, body AckMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*AckMessagesResponse, error)

	// NackMessagesWithBodyWithResponse request with any body
	NackMessagesWithBodyWithResponse(ctx context.Context, subscriptionId SubscriptionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NackMessagesResponse, error)

	NackMessagesWithResponse(ctx context.Context, subscriptionId SubscriptionId, body NackMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*NackMessagesResponse, error)

	// PullMessagesWithResponse request
	PullMessagesWithResponse(ctx context.Context, subscriptionId SubscriptionId, params *PullMessagesParams, reqEditors ...RequestEditorFn) (*PullMessagesResponse, error)
}

type PublishMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PublishMessageResponse
}

// Status returns HTTPResponse.Status
func (r PublishMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublishMessagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PurgeTopicResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PurgeTopicResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PurgeTopicResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PurgeTopicResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AckMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r AckMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AckMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AckMessagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type NackMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r NackMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NackMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r NackMessagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PullMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Messages
}

// Status returns HTTPResponse.Status
func (r PullMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PullMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PullMessagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PublishMessagesWithBodyWithResponse request with arbitrary body returning *PublishMessagesResponse
func (c *ClientWithResponses) PublishMessagesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishMessagesResponse, error) {
	rsp, err := c.PublishMessagesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishMessagesResponse(rsp)
}

func (c *ClientWithResponses) PublishMessagesWithResponse(ctx context.Context, body PublishMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishMessagesResponse, error) {
	rsp, err := c.PublishMessages(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishMessagesResponse(rsp)
}

// PurgeTopicWithResponse request returning *PurgeTopicResponse
func (c *ClientWithResponses) PurgeTopicWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PurgeTopicResponse, error) {
	rsp, err := c.PurgeTopic(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePurgeTopicResponse(rsp)
}

// AckMessagesWithBodyWithResponse request with arbitrary body returning *AckMessagesResponse
func (c *ClientWithResponses) AckMessagesWithBodyWithResponse(ctx context.Context, subscriptionId SubscriptionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AckMessagesResponse, error) {
	rsp, err := c.AckMessagesWithBody(ctx, subscriptionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAckMessagesResponse(rsp)
}

func (c *ClientWithResponses) AckMessagesWithResponse(ctx context.Context, subscriptionId SubscriptionId, body AckMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*AckMessagesResponse, error) {
	rsp, err := c.AckMessages(ctx, subscriptionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAckMessagesResponse(rsp)
}

// NackMessagesWithBodyWithResponse request with arbitrary body returning *NackMessagesResponse
func (c *ClientWithResponses) NackMessagesWithBodyWithResponse(ctx context.Context, subscriptionId SubscriptionId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NackMessagesResponse, error) {
	rsp, err := c.NackMessagesWithBody(ctx, subscriptionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNackMessagesResponse(rsp)
}

func (c *ClientWithResponses) NackMessagesWithResponse(ctx context.Context, subscriptionId SubscriptionId, body NackMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*NackMessagesResponse, error) {
	rsp, err := c.NackMessages(ctx, subscriptionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNackMessagesResponse(rsp)
}

// PullMessagesWithResponse request returning *PullMessagesResponse
func (c *ClientWithResponses) PullMessagesWithResponse(ctx context.Context, subscriptionId SubscriptionId, params *PullMessagesParams, reqEditors ...RequestEditorFn) (*PullMessagesResponse, error) {
	rsp, err := c.PullMessages(ctx, subscriptionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePullMessagesResponse(rsp)
}

// ParsePublishMessagesResponse parses an HTTP response from a PublishMessagesWithResponse call
func ParsePublishMessagesResponse(rsp *http.Response) (*PublishMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PublishMessageResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePurgeTopicResponse parses an HTTP response from a PurgeTopicWithResponse call
func ParsePurgeTopicResponse(rsp *http.Response) (*PurgeTopicResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PurgeTopicResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseAckMessagesResponse parses an HTTP response from a AckMessagesWithResponse call
func ParseAckMessagesResponse(rsp *http.Response) (*AckMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AckMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseNackMessagesResponse parses an HTTP response from a NackMessagesWithResponse call
func ParseNackMessagesResponse(rsp *http.Response) (*NackMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NackMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePullMessagesResponse parses an HTTP response from a PullMessagesWithResponse call
func ParsePullMessagesResponse(rsp *http.Response) (*PullMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PullMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Messages
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
